version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    working_directory: ~/ecs_backend/src
    steps:
      # gitのrepositoryをコピー
      - checkout:
          path: ~/ecs_backend
      #orbsのjobでbunde install
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.1
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: app_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      # 自身のPCを指定
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/ecs_backend/src
    steps:
      - checkout:
          path: ~/ecs_backend
      #orbsのjobでbunde install
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
