version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    working_directory: ~/ecs_backend/src
    steps:
      # gitのrepositoryをコピー
      - checkout:
          path: ~/ecs_backend
      #orbsのjobでbunde install
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.1
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          # 自身のPCを指定
          DB_HOST: 127.0.0.1
          RAILS_ENV: "test"
      - image: cimg/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DB: app_test
    working_directory: ~/ecs_backend/src
    steps:
      - checkout:
          path: ~/ecs_backend
      #orbsのjobでbunde install
      - ruby/install-deps
      - run: cp ../circleci/database.yml.ci config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
